version: "3"
services:
#  loki:
#    image: loki:1.0.0
#    environment:
#      - SERVICE_PORT=3001
#      - MONGO_URI=mongodb://root:password@mongo/accounting_app?authSource=admin
#      - MONGO_DATABASE=accounting_app
#    ports:
#      - 3001:3001

  mongo:
    image: mongo:3.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  mongoex:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - 8081:8081

